rpc_urls = ["http://localhost:32786", "http://localhost:8080"]
root_private_keys = [
    "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80",
    "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d",
]
refresh_delay_secs = 5
use_receipts = false
use_receipts_by_block = false
use_get_logs = false
chain_id = 20_143
min_native_amount = "100000000000000000000"
seed_native_amount = "1000000000000000000000"
debug_log_file = false
trace_log_file = false
use_static_tps_interval = false
otel_replica_name = "default"

[[workload_groups]]
name = "many_to_many"
runtime_minutes = 1

[[workload_groups.traffic_gens]]
tps = 200
recipient_seed = 10_101
sender_seed = 10_101
recipients = 100_000
senders = 1_000
erc20_balance_of = false
sender_group_size = 10
tx_per_sender = 50
gen_mode.few_to_many = { tx_type = "erc20" }