[package]
name = "monad-wireauth-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
zerocopy = { workspace = true, features = ["derive"] }
blake3.workspace = true
aegis.workspace = true
monad-secp = { path = "../monad-secp" }
rand.workspace = true
secp256k1 = { workspace = true, features = ["rand"] }
tai64.workspace = true
bytes.workspace = true
thiserror.workspace = true
zeroize = { workspace = true, features = ["derive"] }
tracing.workspace = true
hex.workspace = true

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
