[package]
name = "monad-txgen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "txgen"
path = "src/main.rs"

[dependencies]
monad-secp = { workspace = true }
monad-types = { workspace = true }
monad-version = { workspace = true }

alloy-consensus = { workspace = true, features = ["k256"] }
alloy-eips = { workspace = true }
alloy-json-rpc = { workspace = true }
alloy-network = { workspace = true }
alloy-primitives = { workspace = true, features = ["rand"] }
alloy-rlp = { workspace = true }
alloy-rpc-client = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
alloy-rpc-types-trace = { workspace = true }
alloy-signer = { workspace = true }
alloy-signer-local = { workspace = true }
alloy-sol-macro = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-transport = { workspace = true }
alloy-transport-http = { workspace = true, features = ["reqwest-rustls-tls"] }
async-channel = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive"] }
dashmap = { workspace = true }
eyre = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
opentelemetry = { workspace = true }
opentelemetry_sdk = { workspace = true, features = ["rt-tokio"] }
opentelemetry-otlp = { workspace = true, features = ["metrics", "grpc-tonic"] }
opentelemetry-semantic-conventions = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
tokio-tungstenite = { workspace = true, features = ["native-tls"] }
toml = { workspace = true }
tracing = { workspace = true, features = ["log", "std"] }
tracing-subscriber = { workspace = true, features = [
    "env-filter",
    "json",
    "std",
] }
url = { workspace = true }

[build-dependencies]
monad-version = { workspace = true }
